export const allJobsData = [
  {
    id: 'fullstack-eng',
    title: 'Full Stack Engineer',
    department: 'Engineering',
    location: 'Hyderabad, India',
    experience: '3-6 Years',
    employmentType: 'Full-time',
    workMode: 'Remote',
    badge: 'Engineering',
    type: 'Full-time • Remote',
    desc: 'Design and build high-performance React frontends and Node.js microservices.',
    summary:
      'We are looking for a Full Stack Engineer to join our core engineering team. You will work on building scalable, high-performance web applications using modern JavaScript frameworks, collaborating with cross-functional teams to deliver impactful products.',
    responsibilities: [
      'Develop complex React-based frontend applications and components',
      'Build and maintain scalable RESTful APIs and Node.js microservices',
      'Write clean, maintainable, and well-documented code',
      'Participate in code reviews and team collaboration sessions',
      'Collaborate with designers and product managers to ship features',
      'Optimize application performance and database queries for scalability',
    ],
    requiredSkills: [
      'React.js, Next.js, TypeScript',
      'Node.js, Express.js',
      'RESTful APIs & GraphQL',
      'Git, CI/CD pipelines',
      'SQL & NoSQL databases (PostgreSQL, MongoDB)',
    ],
    preferredSkills: [
      'Experience with AWS / GCP',
      'Familiarity with Docker & Kubernetes',
      'Understanding of microservices architecture',
    ],
    softSkills: ['Excellent Communication', 'Team Player', 'Problem Solving', 'Adaptability'],
    benefits:
      'Competitive salary, flexible work hours, health insurance, learning stipend, annual retreats, and stock options.',
    iconClass: 'icon-box-blue',
    accentClass: 'accent-blue',
  },
  {
    id: 'mern-eng',
    title: 'MERN Stack Engineer',
    department: 'Engineering',
    location: 'Bangalore, India',
    experience: '2-5 Years',
    employmentType: 'Full-time',
    workMode: 'Hybrid',
    badge: 'Engineering',
    type: 'Full-time • Hybrid',
    desc: 'Develop robust, interactive web applications using MongoDB, Express, React, and Node.',
    summary:
      'We are looking for an experienced MERN Stack Engineer to design and implement robust database schemas, secure API endpoints, and fluid user interfaces for our core cloud platform.',
    responsibilities: [
      'Implement responsive and fluid user interfaces in React.js',
      'Develop secure API endpoints and authentication handlers with Express.js and Node.js',
      'Design, maintain, and query MongoDB databases efficiently',
      'Integrate third-party services, webhooks, and payment gateways',
      'Perform regular debugging, unit testing, and deployment workflows',
      'Collaborate with engineering leads to define API protocols and layouts',
    ],
    requiredSkills: [
      'MongoDB & Mongoose schemas',
      'Express.js & Node.js backend logic',
      'React.js & State Management (Redux/Context)',
      'Modern JavaScript (ES6+) & TypeScript',
      'RESTful API architecture & JWT Auth',
    ],
    preferredSkills: [
      'Familiarity with Docker containers',
      'Experience with AWS deployment (S3, EC2)',
      'Knowledge of TailwindCSS & Framer Motion',
    ],
    softSkills: ['Excellent Communication', 'Team Player', 'Problem Solving', 'Adaptability'],
    benefits:
      'Competitive salary, remote-first/hybrid balance, health coverage, conference allowances, and direct performance bonuses.',
    iconClass: 'icon-box-purple',
    accentClass: 'accent-purple',
  },
  {
    id: 'cloud-eng',
    title: 'Cloud Solutions Architect',
    department: 'Cloud',
    location: 'Bangalore, India',
    experience: '5-9 Years',
    employmentType: 'Full-time',
    workMode: 'Remote',
    badge: 'Cloud',
    type: 'Full-time • Remote',
    desc: 'Architect secure, highly available cloud infrastructures and serverless solutions.',
    summary:
      'As a Cloud Solutions Architect you will design and implement enterprise-grade cloud architectures on AWS, Azure, and GCP. You will guide migration strategies and ensure best practices in security, cost optimization, and reliability.',
    responsibilities: [
      'Design multi-cloud and hybrid-cloud architectures',
      'Lead cloud migration and modernization initiatives',
      'Implement Infrastructure as Code (Terraform, CloudFormation)',
      'Ensure security best practices and compliance',
      'Optimize cloud costs and resource utilization',
      'Collaborate with DevOps and engineering teams',
    ],
    requiredSkills: [
      'AWS, Azure, or GCP (certified preferred)',
      'Terraform, CloudFormation, Pulumi',
      'Networking (VPC, DNS, Load Balancers)',
      'Containerization (Docker, Kubernetes, ECS)',
      'Security & IAM best practices',
    ],
    preferredSkills: [
      'Serverless architecture (Lambda, Functions)',
      'Multi-cloud strategy experience',
      'FinOps and cloud cost management',
    ],
    softSkills: ['Excellent Communication', 'Team Player', 'Problem Solving', 'Adaptability'],
    benefits:
      'Competitive salary, remote-first culture, cloud certification sponsorship, health benefits, and performance bonuses.',
    iconClass: 'icon-box-purple',
    accentClass: 'accent-purple',
  },
  {
    id: 'devops-eng',
    title: 'DevOps & Platform Engineer',
    department: 'DevOps',
    location: 'Hyderabad, India',
    experience: '3-6 Years',
    employmentType: 'Full-time',
    workMode: 'Hybrid',
    badge: 'DevOps',
    type: 'Full-time • Hybrid',
    desc: 'Build CI/CD pipelines, automate infrastructure, and optimize platform reliability.',
    summary:
      'We are hiring a DevOps & Platform Engineer to build and maintain our CI/CD pipelines, automate infrastructure provisioning, and ensure high availability of production systems.',
    responsibilities: [
      'Design and maintain CI/CD pipelines (Jenkins, GitHub Actions, GitLab CI)',
      'Automate infrastructure provisioning with Terraform and Ansible',
      'Monitor systems using Prometheus, Grafana, and ELK stack',
      'Manage container orchestration with Kubernetes',
      'Implement site reliability engineering (SRE) practices',
      'Respond to production incidents and conduct post-mortems',
    ],
    requiredSkills: [
      'Linux administration & shell scripting',
      'Docker, Kubernetes, Helm',
      'CI/CD tools (Jenkins, GitHub Actions)',
      'Terraform, Ansible',
      'Monitoring (Prometheus, Grafana, Datadog)',
    ],
    preferredSkills: [
      'Experience with service mesh (Istio)',
      'GitOps workflows (ArgoCD, Flux)',
      'Chaos engineering practices',
    ],
    softSkills: ['Excellent Communication', 'Team Player', 'Problem Solving', 'Adaptability'],
    benefits:
      'Competitive salary, hybrid work model, health insurance, annual learning budget, and team outings.',
    iconClass: 'icon-box-pink',
    accentClass: 'accent-pink',
  },
  {
    id: 'qa-eng',
    title: 'Automation QA Engineer',
    department: 'Quality',
    location: 'Pune, India',
    experience: '2-5 Years',
    employmentType: 'Full-time',
    workMode: 'Hybrid',
    badge: 'Quality',
    type: 'Full-time • Hybrid',
    desc: 'Develop robust automated test frameworks to maintain top-tier software reliability.',
    summary:
      'Join our quality engineering team to build and maintain automated testing frameworks. You will ensure product quality across web and mobile platforms through comprehensive test strategies.',
    responsibilities: [
      'Design and develop automated test suites (Selenium, Cypress, Playwright)',
      'Create and maintain API test frameworks (Postman, RestAssured)',
      'Integrate tests into CI/CD pipelines',
      'Perform performance and load testing',
      'Collaborate with developers to improve code quality',
      'Document test plans and report defects effectively',
    ],
    requiredSkills: [
      'Selenium, Cypress, or Playwright',
      'JavaScript / TypeScript or Java',
      'API testing (Postman, RestAssured)',
      'CI/CD integration for test automation',
      'Agile/Scrum methodologies',
    ],
    preferredSkills: [
      'Performance testing (JMeter, k6)',
      'Mobile testing (Appium)',
      'BDD frameworks (Cucumber)',
    ],
    softSkills: ['Excellent Communication', 'Team Player', 'Problem Solving', 'Adaptability'],
    benefits:
      'Competitive salary, flexible hours, certification support, health benefits, and career growth opportunities.',
    iconClass: 'icon-box-blue',
    accentClass: 'accent-blue',
  },
  {
    id: 'sec-spec',
    title: 'Cybersecurity Analyst',
    department: 'Security',
    location: 'Hyderabad, India',
    experience: '3-7 Years',
    employmentType: 'Full-time',
    workMode: 'Remote',
    badge: 'Security',
    type: 'Full-time • Remote',
    desc: 'Monitor network security logs, assess vulnerabilities, and implement compliance.',
    summary:
      'We are seeking an experienced Cybersecurity Analyst to protect our infrastructure and data. You will monitor threats, assess vulnerabilities, and drive compliance across the organization.',
    responsibilities: [
      'Monitor SIEM systems and analyze security events',
      'Conduct vulnerability assessments and penetration testing',
      'Implement and manage security policies and compliance frameworks',
      'Respond to security incidents and lead forensic investigations',
      'Collaborate with engineering to embed security into the SDLC',
      'Stay current with emerging threats and security trends',
    ],
    requiredSkills: [
      'SIEM tools (Splunk, QRadar, Sentinel)',
      'Vulnerability scanning (Nessus, Qualys)',
      'Network security (firewalls, IDS/IPS)',
      'Compliance frameworks (ISO 27001, SOC 2, GDPR)',
      'Incident response & digital forensics',
    ],
    preferredSkills: [
      'OSCP, CEH, or CISSP certification',
      'Cloud security (AWS Security Hub, Azure Defender)',
      'Zero Trust architecture experience',
    ],
    softSkills: ['Excellent Communication', 'Team Player', 'Problem Solving', 'Adaptability'],
    benefits:
      'Competitive salary, remote-first, security certification sponsorship, health coverage, and flexible PTO.',
    iconClass: 'icon-box-purple',
    accentClass: 'accent-purple',
  },
  {
    id: 'ai-ml-eng',
    title: 'AI / ML Engineer',
    department: 'Engineering',
    location: 'Bangalore, India',
    experience: '3-6 Years',
    employmentType: 'Full-time',
    workMode: 'Remote',
    badge: 'AI/ML',
    type: 'Full-time • Remote',
    desc: 'Build and deploy machine learning models and AI-powered features at scale.',
    summary:
      'Join our AI team to design, train, and deploy machine learning models that power intelligent features across our product suite. You will work with large datasets and cutting-edge frameworks.',
    responsibilities: [
      'Design and train ML models for classification, NLP, and recommendation',
      'Build data pipelines for feature engineering',
      'Deploy models using MLOps best practices',
      'Evaluate model performance and iterate on improvements',
      'Collaborate with product and engineering teams',
      'Research and prototype new AI capabilities',
    ],
    requiredSkills: [
      'Python, TensorFlow, PyTorch',
      'Scikit-learn, Pandas, NumPy',
      'NLP, Computer Vision, or Recommendation Systems',
      'SQL and data pipeline tools',
      'Model deployment (MLflow, SageMaker, Vertex AI)',
    ],
    preferredSkills: [
      'LLM fine-tuning and prompt engineering',
      'Distributed training (Horovod, DeepSpeed)',
      'Experience with real-time inference systems',
    ],
    softSkills: ['Excellent Communication', 'Team Player', 'Problem Solving', 'Adaptability'],
    benefits:
      'Competitive salary, GPU compute budget, conference sponsorship, remote-first, and health benefits.',
    iconClass: 'icon-box-pink',
    accentClass: 'accent-pink',
  },
  {
    id: 'data-analyst',
    title: 'Data Analyst',
    department: 'Data',
    location: 'Pune, India',
    experience: '1-4 Years',
    employmentType: 'Full-time',
    workMode: 'Hybrid',
    badge: 'Data',
    type: 'Full-time • Hybrid',
    desc: 'Transform raw data into actionable insights that drive business decisions.',
    summary:
      'We are looking for a Data Analyst to turn complex datasets into actionable business insights. You will build dashboards, perform statistical analysis, and collaborate with stakeholders across the organization.',
    responsibilities: [
      'Build interactive dashboards and reports (Tableau, Power BI)',
      'Perform exploratory data analysis and statistical modeling',
      'Write complex SQL queries for data extraction and transformation',
      'Collaborate with product and business teams to define KPIs',
      'Automate recurring reports and data workflows',
      'Present insights and recommendations to leadership',
    ],
    requiredSkills: [
      'SQL (advanced), Python or R',
      'Tableau, Power BI, or Looker',
      'Statistical analysis and hypothesis testing',
      'Excel / Google Sheets (advanced)',
      'Data modeling and ETL processes',
    ],
    preferredSkills: [
      'Experience with dbt or Airflow',
      'Knowledge of A/B testing frameworks',
      'Familiarity with cloud data warehouses (BigQuery, Snowflake)',
    ],
    softSkills: ['Excellent Communication', 'Team Player', 'Problem Solving', 'Adaptability'],
    benefits:
      'Competitive salary, hybrid work, learning stipend, health insurance, and team events.',
    iconClass: 'icon-box-blue',
    accentClass: 'accent-blue',
  },
  {
    id: 'product-designer',
    title: 'Senior Product Designer',
    department: 'Design',
    location: 'Bangalore, India',
    experience: '4-8 Years',
    employmentType: 'Full-time',
    workMode: 'Remote',
    badge: 'Design',
    type: 'Full-time • Remote',
    desc: 'Craft intuitive, pixel-perfect user experiences for enterprise SaaS products.',
    summary:
      'We are hiring a Senior Product Designer to lead the design of our enterprise SaaS products. You will own the end-to-end design process from user research to high-fidelity prototypes and design systems.',
    responsibilities: [
      'Lead end-to-end product design from research to delivery',
      'Create wireframes, prototypes, and high-fidelity mockups',
      'Build and maintain a scalable design system',
      'Conduct user research and usability testing',
      'Collaborate closely with engineering and product teams',
      'Champion accessibility and inclusive design practices',
    ],
    requiredSkills: [
      'Figma (expert level)',
      'Design systems and component libraries',
      'User research and usability testing',
      'Prototyping and interaction design',
      'Visual design and typography',
    ],
    preferredSkills: [
      'Motion design (Lottie, After Effects)',
      'HTML/CSS for design handoff',
      'Experience with enterprise / B2B SaaS products',
    ],
    softSkills: ['Excellent Communication', 'Team Player', 'Problem Solving', 'Adaptability'],
    benefits:
      'Competitive salary, remote-first, design tool budget, conference attendance, health insurance, and flexible PTO.',
    iconClass: 'icon-box-purple',
    accentClass: 'accent-purple',
  }
];
